define('gunmaps', function () {
    names = {
        "Item_Weapon_HK416_C": ["M416","default-gun"],
        "Item_Weapon_SKS_C": ["SKS","SKS"],
        "Item_Weapon_FNFal_C": ["SLR",null],
        "Item_Weapon_AK47_C": ["AKM","AKM"],
        "Item_Weapon_Kar98k_C": ["Kar98k","Kar98k"],
        "Item_Weapon_Mini14_C": ["Mini14","mini14"],
        "Item_Weapon_SCAR-L_C": ["SCAR-L","SCAR-L"],
        "Item_Weapon_M24_C": ["M24","M24"],
        "Item_Weapon_M16A4_C": ["M16A4","M16A4"],
        "Item_Weapon_G36C_C": ["G36C",""],
        "Item_Weapon_QBZ95_C": ["QBZ",""],
        "Item_Weapon_UMP_C": ["UMP45","UMP45"],
        "Item_Weapon_BerylM762_C": ["BeryI-M762",null],
        "Item_Weapon_Mk47Mutant_C": ["Mk47",null],
        "Item_Weapon_QBU88_C": ["QBU",null],
        "Item_Weapon_UZI_C": ["Micro-UZI","UZI"],
        "Item_Weapon_MK14_C": ["Mk14","MK14"],
        "Item_Weapon_MP5K_C": ["MP5K",null],
        "Item_Weapon_Vector_C": ["Vector","VECTOR"],
        "Item_Weapon_AWM_C": ["AWM","AWM"],
        "Item_Weapon_Win1894_C": ["Win94",""],
        "Item_Weapon_Thompson_C": ["汤姆逊","Thompson"],
        "Item_Weapon_Saiga12_C": ["S12K","S12K"],
        "Item_Weapon_BizonPP19_C": ["PP-19",""],
        "Item_Weapon_Crossbow_C": ["十字弩","crossbow"],
        "Item_Weapon_AUG_C": ["AUG",null],
        "Item_Weapon_Winchester_C": ["S1897","S1897"],
        "Item_Weapon_Mosin_C": ["MosinNagant",null],
        "Item_Weapon_Groza_C": ["Groza","GROZA"],
        "Item_Weapon_M249_C": ["M249","M249"],
        "Item_Weapon_Berreta686_C": ["S686","S686"],
        "Item_Weapon_DP28_C": ["DP-28","DP28"],
        "Item_Weapon_M9_C": ["P92","P92"],
        "Item_Weapon_M1911_C": ["P1911","P1911"],
        "Item_Weapon_NagantM1895_C": ["R1895","R1895"],
        "Item_Weapon_vz61Skorpion_C": ["Skorpion",null],
        "Item_Weapon_DP12_C": ["DBS",null],
        "Item_Weapon_Sawnoff_C": ["截短散弹枪", 'sawnoff'],
        "Item_Weapon_Rhino_C": ["R45",'R45'],
        "Item_Weapon_DesertEagle_C": ["沙漠之鹰",null],
        "Item_Weapon_G18_C": ["P18C",null],
        "Item_Weapon_VSS_C": ["VSS","VSS"]
    }
    return names
})